### ISSUE TITLE
cluster_sizeMCDS bug when having a single value

### ISSUE THREAD

**Issue by frousseu** [RoyChristian/GeoAviR#10]
When there is a single value for counts (e.g. all 10 observations are 2s), cluster_sizeMCDS gives a warning and generates some NAs. Not sure yet if this is the exact problem, need to further investigate. I am just writing it down here so as not to forget about this problem.

**Comment by RoyChristian** [comment]
Hi François, this is an issue within Distance itself when you are fitting a model with the Cluster as a an explanatory variable but there is no variance in cluster size (Internal Error Message # 32; page 342 in the Distance 6.2 user manual)
