### ISSUE TITLE
Point Count Surveys unable to run

### ISSUE THREAD

**Issue by gledits2** [RoyChristian/GeoAviR#15]
I am trying to run point count data through mcds.wrap and am getting an error each time. From the publication it seems like R2MCDS can't handle continuous distance data yet but the MCDS engine (program Distance) requires continuous distance data for point counts. 

When I try to run the mcds.wrap funtion it seems like it runs but nothing is returned. Before today when I ran the code I got an error pertaining to the Distance Units being wrong.

Here is the first 6 lines of my data:
point_count_station_id	survey_id                 			samp_date	long      
EKA-PC01		        EKA-PC01_14_March_2015		3/14/2015	-158.0806 
EKA-PC01	         	EKA-PC01_14_March_2015		3/14/2015	-158.0806 
EKA-PC01	        	EKA-PC01_26_January_2016   	1/26/2016	-158.0806 
EKA-PC01	         	EKA-PC01_26_January_2016    	1/26/2016	-158.0806 
EKA-PC01	        	EKA-PC01_14_March_2015		3/14/2015	-158.0806 
EKA-PC01	        	EKA-PC01_14_March_2015		3/14/2015	-158.0806 

lat	  	        radius	species	distance_m	direction_degrees	dist_class 
21.44356 	40    	WRSH	37	        	307   			D		
21.44356 	40	        JAWE	29    		338   			C		
21.44356 	40    	RBLE	33    		262   			D		
21.44356 	40    	ZEBD	36    		322  			D		
21.44356 	40    	JAWE	38    		52    			D		
21.44356 	40    	RBLE	29    		279  			C		

count	wind_class	rain_class
1      	1       		0
2      	1      		0
1      	0       		0
1      	0      		0
2      	3      		0
2       	3      		0

And here is my code and the output I get:
df.pc01 <- mcds.filter(pc.eka.pc01, transect.id = "survey_id", distance.field = "dist_class", 
                   distance.labels = c("A", "B", "C", "D"), 
                   distance.midpoints = c(5, 15, 25, 35), 
                   effort.field = "radius", sp.field = "species", date.field = "samp_date",
		   lat.field = "lat", long.field = "long",)

mod1 <- mcds.wrap(df.pc01,SMP_EFFORT="WatchLenKm",
                  DISTANCE="Distance",SIZE="count",
                  units=list(Type="Point",Distance="Radial",
                              Length_units="Meters",
                              Distance_units="Meters",
                              Area_units="Square kilometers"),
                  breaks=c(0,10,20,30,40), estimator=list(c("HN","CO")),
                  factor = c("wind_class","rain_class"), monotone = "none", 
		  split=FALSE,
                  STR_LABEL="STR_LABEL",STR_AREA="STR_AREA",SMP_LABEL="WatchID",
                  path="D:/temp/distance",
                  pathMCDS="C:/Program Files (x86)/Distance 7",verbose=FALSE)
#3
#Warning message:
#running command '"C:\Program Files (x86)\Distance 7/MCDS" 0, #"d:\temp\distance/input__HN_CO.tmp"' had status 3 

mod1
#list()
#attr(,"class")
#[1] "speciesList"

summary(mod1)
#     Length       Class        Mode 
#          0 speciesList        list 

Any help you could provide would be most appreciated. Thanks

**Comment by gledits2** [comment]
Sorry when I submitted this issue github did weird things with the text formatting. Please let me know if you need me to resubmit any information.

**Comment by RoyChristian** [comment]
After lengthy delays it should be possible to analyze points counts with R2MCDS Version 0.9.2
